name: Update streak stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GitHub Readme Streak Stats Action
        uses: DenverCoder1/github-readme-streak-stats@v1.7.0
        with:
          options: 'user=msalihberk&theme=tokyonight&hide_border=true'
          path: 'profile-streak-stats.svg'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push updated SVG
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add profile-streak-stats.svg
          git commit -m "chore: update github streak stats" || exit 0
          git push
          
